-- Annual OU-level Gender and Development PIMME assessments.
-- This migration is additive and does not alter existing LOD or Drive records.

insert into public.roles_config (role, module, can_view, can_edit, can_delete, can_manage, visibility_scope)
select role, 'Gender and Development', can_view, can_edit, can_delete, can_manage, visibility_scope
from public.roles_config source
where source.module = 'Level of Development'
  and not exists (
    select 1 from public.roles_config target
    where target.role = source.role and target.module = 'Gender and Development'
  );

create table if not exists public.gad_pimme_assessments (
  id bigint generated by default as identity primary key,
  operating_unit text not null,
  year integer not null,
  checklist_version text not null default 'PIMME-2026-v1',
  box16_score numeric(6,2) not null default 0,
  box17_score numeric(6,2) not null default 0,
  total_score numeric(6,2) not null default 0,
  answered_count integer not null default 0,
  status text not null default 'Incomplete',
  created_by bigint references public.users(id) on delete set null,
  created_by_name text,
  updated_by bigint references public.users(id) on delete set null,
  updated_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint gad_pimme_assessments_ou_year_unique unique (operating_unit, year),
  constraint gad_pimme_assessments_year_check check (year between 2019 and 2200),
  constraint gad_pimme_assessments_score_check check (
    box16_score between 0 and 8 and box17_score between 0 and 12 and total_score between 0 and 20
  ),
  constraint gad_pimme_assessments_answered_check check (answered_count between 0 and 22),
  constraint gad_pimme_assessments_status_check check (status in ('Incomplete', 'Completed'))
);

create table if not exists public.gad_pimme_answers (
  id bigint generated by default as identity primary key,
  assessment_id bigint not null references public.gad_pimme_assessments(id) on delete cascade,
  question_key text not null,
  response text,
  points_earned numeric(6,2) not null default 0,
  remarks text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint gad_pimme_answers_assessment_question_unique unique (assessment_id, question_key),
  constraint gad_pimme_answers_response_check check (response is null or response in ('No', 'Partly Yes', 'Yes'))
);

create table if not exists public.gad_pimme_folders (
  id bigint generated by default as identity primary key,
  connection_id uuid not null references public.google_drive_connections(id) on delete cascade,
  year integer not null,
  operating_unit text not null,
  module_folder_id text not null,
  year_folder_id text not null,
  operating_unit_folder_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint gad_pimme_folders_identity_unique unique (connection_id, year, operating_unit)
);

create table if not exists public.gad_pimme_files (
  id bigint generated by default as identity primary key,
  assessment_id bigint not null references public.gad_pimme_assessments(id) on delete cascade,
  question_key text not null,
  connection_id uuid references public.google_drive_connections(id) on delete set null,
  folder_id text not null,
  file_id text not null,
  file_name text not null,
  mime_type text,
  file_size bigint not null default 0,
  web_view_link text,
  web_content_link text,
  preview_url text,
  uploaded_by bigint references public.users(id) on delete set null,
  uploaded_by_name text,
  uploaded_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint gad_pimme_files_drive_file_unique unique (file_id)
);

create index if not exists gad_pimme_assessments_year_ou_idx
on public.gad_pimme_assessments (year desc, operating_unit);

create index if not exists gad_pimme_files_assessment_question_idx
on public.gad_pimme_files (assessment_id, question_key, uploaded_at desc)
where deleted_at is null;

create or replace function public.gad_pimme_points(p_question_key text, p_response text)
returns numeric
language sql
immutable
strict
as $$
  select case
    when p_response = 'No' then 0
    when p_question_key in ('box16-1.1','box16-1.2','box16-3.1','box16-3.2','box17-1.1','box17-1.2','box17-5.1','box17-5.2')
      then case when p_response = 'Partly Yes' then 0.5 when p_response = 'Yes' then 1 end
    when p_question_key in ('box16-2.1','box16-2.2','box16-2.3')
      then case when p_response = 'Partly Yes' then 0.33 when p_response = 'Yes' then 0.67 end
    when p_question_key in ('box16-4.1','box16-4.2','box16-4.3','box16-4.4','box17-2.1','box17-2.2','box17-2.3','box17-2.4')
      then case when p_response = 'Partly Yes' then 0.25 when p_response = 'Yes' then 0.5 end
    when p_question_key in ('box17-3.1','box17-3.2','box17-4.0')
      then case when p_response = 'Partly Yes' then 1 when p_response = 'Yes' then 2 end
    else null
  end;
$$;

create or replace function public.save_gad_pimme_assessment(
  p_operating_unit text,
  p_year integer,
  p_answers jsonb,
  p_actor_id bigint,
  p_actor_name text
)
returns public.gad_pimme_assessments
language plpgsql
security definer
set search_path = public
as $$
declare
  actor public.users%rowtype;
  permission public.roles_config%rowtype;
  saved public.gad_pimme_assessments%rowtype;
  item jsonb;
  item_key text;
  item_response text;
  item_remarks text;
  item_points numeric;
  answer_count integer;
  box16 numeric;
  box17 numeric;
  allowed_edit boolean;
  allowed_scope text;
begin
  select * into actor from public.users where id = p_actor_id;
  if actor.id is null then raise exception 'The assessment user could not be resolved.'; end if;
  select * into permission from public.roles_config
  where role = actor.role and module = 'Gender and Development' limit 1;
  allowed_edit := case
    when jsonb_typeof(actor.permissions_override->'Gender and Development'->'can_edit') = 'boolean'
      then (actor.permissions_override->'Gender and Development'->>'can_edit')::boolean
    else coalesce(permission.can_edit, false)
  end;
  if not allowed_edit then
    raise exception 'You do not have permission to edit Gender and Development assessments.';
  end if;
  allowed_scope := case
    when actor.visibility_scope in ('All OUs', 'Own OU') then actor.visibility_scope
    else coalesce(permission.visibility_scope, 'Own OU')
  end;
  if allowed_scope <> 'All OUs' and actor."operatingUnit" <> p_operating_unit then
    raise exception 'The selected operating unit is outside your configured visibility scope.';
  end if;
  if p_year < 2019 or p_year > extract(year from current_date)::integer then
    raise exception 'The assessment year is not supported.';
  end if;
  if jsonb_typeof(coalesce(p_answers, '[]'::jsonb)) <> 'array' then
    raise exception 'Assessment answers must be an array.';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_answers) entry
    group by entry->>'question_key' having count(*) > 1
  ) then raise exception 'The assessment contains duplicate question entries.'; end if;

  insert into public.gad_pimme_assessments (
    operating_unit, year, checklist_version, created_by, created_by_name, updated_by, updated_by_name
  ) values (
    p_operating_unit, p_year, 'PIMME-2026-v1', actor.id,
    coalesce(nullif(trim(p_actor_name), ''), actor."fullName"), actor.id,
    coalesce(nullif(trim(p_actor_name), ''), actor."fullName")
  )
  on conflict (operating_unit, year) do update set
    checklist_version = excluded.checklist_version,
    updated_by = excluded.updated_by,
    updated_by_name = excluded.updated_by_name,
    updated_at = now()
  returning * into saved;

  delete from public.gad_pimme_answers where assessment_id = saved.id;
  for item in select value from jsonb_array_elements(p_answers) loop
    item_key := nullif(trim(item->>'question_key'), '');
    item_response := nullif(trim(item->>'response'), '');
    item_remarks := nullif(item->>'remarks', '');
    if item_key is null or item_key not in (
      'box16-1.1','box16-1.2','box16-2.1','box16-2.2','box16-2.3','box16-3.1','box16-3.2',
      'box16-4.1','box16-4.2','box16-4.3','box16-4.4','box17-1.1','box17-1.2','box17-2.1',
      'box17-2.2','box17-2.3','box17-2.4','box17-3.1','box17-3.2','box17-4.0','box17-5.1','box17-5.2'
    ) then
      raise exception 'Unknown PIMME question key: %.', coalesce(item_key, '(blank)');
    end if;
    if item_response is not null and item_response not in ('No', 'Partly Yes', 'Yes') then
      raise exception 'Invalid PIMME response for %.', item_key;
    end if;
    item_points := case when item_response is null then 0 else public.gad_pimme_points(item_key, item_response) end;
    if item_response is not null or item_remarks is not null then
      insert into public.gad_pimme_answers (assessment_id, question_key, response, points_earned, remarks)
      values (saved.id, item_key, item_response, item_points, item_remarks);
    end if;
  end loop;

  select count(*) filter (where response is not null) into answer_count
  from public.gad_pimme_answers where assessment_id = saved.id;

  select round(
    least(2, coalesce(sum(points_earned) filter (where question_key like 'box16-1.%'), 0)) +
    least(2, coalesce(sum(points_earned) filter (where question_key like 'box16-2.%'), 0)) +
    least(2, coalesce(sum(points_earned) filter (where question_key like 'box16-3.%'), 0)) +
    least(2, coalesce(sum(points_earned) filter (where question_key like 'box16-4.%'), 0)), 2
  ) into box16 from public.gad_pimme_answers where assessment_id = saved.id;

  select round(
    least(2, coalesce(sum(points_earned) filter (where question_key like 'box17-1.%'), 0)) +
    least(2, coalesce(sum(points_earned) filter (where question_key like 'box17-2.%'), 0)) +
    least(4, coalesce(sum(points_earned) filter (where question_key like 'box17-3.%'), 0)) +
    least(2, coalesce(sum(points_earned) filter (where question_key = 'box17-4.0'), 0)) +
    least(2, coalesce(sum(points_earned) filter (where question_key like 'box17-5.%'), 0)), 2
  ) into box17 from public.gad_pimme_answers where assessment_id = saved.id;

  update public.gad_pimme_assessments set
    box16_score = least(8, coalesce(box16, 0)),
    box17_score = least(12, coalesce(box17, 0)),
    total_score = least(20, coalesce(box16, 0) + coalesce(box17, 0)),
    answered_count = coalesce(answer_count, 0),
    status = case when answer_count = 22 then 'Completed' else 'Incomplete' end,
    updated_by = actor.id,
    updated_by_name = coalesce(nullif(trim(p_actor_name), ''), actor."fullName"),
    updated_at = now()
  where id = saved.id returning * into saved;

  return saved;
end;
$$;

alter table public.gad_pimme_assessments disable row level security;
alter table public.gad_pimme_answers disable row level security;
alter table public.gad_pimme_folders disable row level security;
alter table public.gad_pimme_files disable row level security;

revoke insert, update, delete on public.gad_pimme_assessments from anon, authenticated;
revoke insert, update, delete on public.gad_pimme_answers from anon, authenticated;
grant select on public.gad_pimme_assessments, public.gad_pimme_answers to anon, authenticated;
revoke all on public.gad_pimme_folders, public.gad_pimme_files from anon, authenticated;
grant all on public.gad_pimme_assessments, public.gad_pimme_answers, public.gad_pimme_folders, public.gad_pimme_files to service_role;
revoke all on function public.save_gad_pimme_assessment(text, integer, jsonb, bigint, text) from public;
grant execute on function public.save_gad_pimme_assessment(text, integer, jsonb, bigint, text) to anon, authenticated;
