-- Additive identity migration for 4KISTest.
-- This deliberately keeps every legacy name/ID snapshot for staged dual-read/dual-write compatibility.

alter table public.activities
  add column if not exists activity_title text;

comment on column public.activities.activity_title is
  'Specific occurrence title. reference_activity_id remains the generic configured activity type.';

-- Existing training names are already specific titles. Generic activities are intentionally not guessed.
update public.activities
set activity_title = nullif(btrim(name), '')
where activity_title is null
  and type = 'Training'
  and nullif(btrim(name), '') is not null;

create table if not exists public.activity_ipos (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  ipo_id bigint not null references public.ipos(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  constraint activity_ipos_activity_id_ipo_id_key unique (activity_id, ipo_id)
);

create index if not exists activity_ipos_activity_id_idx
  on public.activity_ipos (activity_id);

create index if not exists activity_ipos_ipo_id_idx
  on public.activity_ipos (ipo_id);

drop trigger if exists activity_ipos_set_updated_at on public.activity_ipos;
create trigger activity_ipos_set_updated_at
before update on public.activity_ipos
for each row execute function public.update_updated_at_column();

grant select, insert, update, delete on table public.activity_ipos to anon, authenticated, service_role;
grant usage, select on sequence public.activity_ipos_id_seq to anon, authenticated, service_role;

-- First backfill activity relationships from the existing immutable ID snapshots.
insert into public.activity_ipos (activity_id, ipo_id, created_by)
select distinct
  activity.id,
  ipo.id,
  'migration:legacy participating_ipo_ids'
from public.activities activity
cross join lateral jsonb_array_elements_text(
  case
    when jsonb_typeof(coalesce(activity.participating_ipo_ids, '[]'::jsonb)) = 'array'
      then coalesce(activity.participating_ipo_ids, '[]'::jsonb)
    else '[]'::jsonb
  end
) legacy_id(value)
join public.ipos ipo
  on ipo.id = case
    when legacy_id.value ~ '^[0-9]+$' then legacy_id.value::bigint
    else null
  end
on conflict (activity_id, ipo_id) do nothing;

-- Then resolve legacy names only when one and only one normalized IPO name matches.
insert into public.activity_ipos (activity_id, ipo_id, created_by)
select distinct
  activity.id,
  resolved.ipo_id,
  'migration:unique normalized participatingIpos name'
from public.activities activity
cross join lateral jsonb_array_elements_text(
  case
    when jsonb_typeof(coalesce(activity."participatingIpos", '[]'::jsonb)) = 'array'
      then coalesce(activity."participatingIpos", '[]'::jsonb)
    else '[]'::jsonb
  end
) legacy_name(value)
join lateral (
  select min(ipo.id) as ipo_id
  from public.ipos ipo
  where lower(regexp_replace(btrim(ipo.name), '\s+', ' ', 'g'))
      = lower(regexp_replace(btrim(legacy_name.value), '\s+', ' ', 'g'))
  having count(*) = 1
) resolved on true
where nullif(btrim(legacy_name.value), '') is not null
on conflict (activity_id, ipo_id) do nothing;

-- Backfill subproject IPO IDs only for unambiguous normalized-name matches.
with subproject_matches as (
  select
    subproject.id as subproject_id,
    min(ipo.id) as ipo_id
  from public.subprojects subproject
  join public.ipos ipo
    on lower(regexp_replace(btrim(ipo.name), '\s+', ' ', 'g'))
      = lower(regexp_replace(btrim(subproject."indigenousPeopleOrganization"), '\s+', ' ', 'g'))
  where subproject.ipo_id is null
    and nullif(btrim(subproject."indigenousPeopleOrganization"), '') is not null
  group by subproject.id
  having count(*) = 1
)
update public.subprojects subproject
set ipo_id = matched.ipo_id
from subproject_matches matched
where subproject.id = matched.subproject_id;

-- Add the relational guard without making the column mandatory during the compatibility phase.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'subprojects_ipo_id_fkey'
      and conrelid = 'public.subprojects'::regclass
  ) then
    alter table public.subprojects
      add constraint subprojects_ipo_id_fkey
      foreign key (ipo_id) references public.ipos(id)
      on delete set null
      not valid;
  end if;
end
$$;

-- Validate only when all existing non-null IDs are legitimate.
do $$
begin
  if not exists (
    select 1
    from public.subprojects subproject
    left join public.ipos ipo on ipo.id = subproject.ipo_id
    where subproject.ipo_id is not null
      and ipo.id is null
  ) then
    alter table public.subprojects validate constraint subprojects_ipo_id_fkey;
  end if;
end
$$;

-- Transitional marketing-linkage repair: add ipoId inside nested JSON only for unique matches.
-- ipoName remains as a display snapshot and unresolved/ambiguous values remain untouched.
with repaired_partners as (
  select
    partner.id as partner_id,
    coalesce(
      jsonb_agg(
        case
          when linkage.item ? 'ipoId' then linkage.item
          when resolved.ipo_id is not null then linkage.item || jsonb_build_object('ipoId', resolved.ipo_id)
          else linkage.item
        end
        order by linkage.ordinality
      ),
      '[]'::jsonb
    ) as linkages
  from public.marketing_partners partner
  cross join lateral jsonb_array_elements(
    case
      when jsonb_typeof(coalesce(partner."marketingLinkages", '[]'::jsonb)) = 'array'
        then coalesce(partner."marketingLinkages", '[]'::jsonb)
      else '[]'::jsonb
    end
  ) with ordinality as linkage(item, ordinality)
  left join lateral (
    select min(ipo.id) as ipo_id
    from public.ipos ipo
    where lower(regexp_replace(btrim(ipo.name), '\s+', ' ', 'g'))
        = lower(regexp_replace(btrim(linkage.item ->> 'ipoName'), '\s+', ' ', 'g'))
    having count(*) = 1
  ) resolved on true
  group by partner.id
)
update public.marketing_partners partner
set "marketingLinkages" = repaired.linkages
from repaired_partners repaired
where partner.id = repaired.partner_id;
