-- LOD carry-over provenance, immutable questionnaire snapshots, and admin-control permission.
-- This migration is additive. It does not recalculate or replace historical scores.

alter table public.roles_config
  add column if not exists can_manage boolean not null default false;

update public.roles_config
set can_manage = true
where module = 'Level of Development'
  and role in ('Super Admin', 'Administrator');

alter table public.lod_sections add column if not exists is_active boolean not null default true;
alter table public.lod_questions add column if not exists is_active boolean not null default true;
alter table public.lod_choices add column if not exists is_active boolean not null default true;

create table if not exists public.lod_questionnaire_versions (
  id bigint generated by default as identity primary key,
  version_number integer not null unique,
  effective_year integer not null,
  label text not null,
  config jsonb not null,
  created_by bigint references public.users(id) on delete set null,
  created_by_name text,
  created_at timestamptz not null default now(),
  constraint lod_questionnaire_versions_effective_year_check check (effective_year between 1900 and 2200),
  constraint lod_questionnaire_versions_config_check check (jsonb_typeof(config) = 'object')
);

alter table public.lod_assessments
  add column if not exists questionnaire_version_id bigint references public.lod_questionnaire_versions(id) on delete restrict,
  add column if not exists carried_over_from_assessment_id integer references public.lod_assessments(id) on delete set null,
  add column if not exists carried_over_from_year integer,
  add column if not exists carried_over_level integer,
  add column if not exists carried_over_total_score numeric;

alter table public.lod_assessments drop constraint if exists lod_assessments_carried_over_level_check;
alter table public.lod_assessments add constraint lod_assessments_carried_over_level_check
  check (carried_over_level is null or carried_over_level between 1 and 5);

create or replace function public.build_lod_questionnaire_config()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'sections', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', section.id,
        'title', section.title,
        'code', section.code,
        'order', section."order",
        'weight', section.weight
      ) order by section."order", section.id)
      from public.lod_sections section
      where section.is_active
    ), '[]'::jsonb),
    'questions', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', question.id,
        'section_id', question.section_id,
        'text', question.text,
        'code', question.code,
        'description', question.description,
        'weight', question.weight,
        'order', question."order",
        'is_calculation_mode', coalesce(question.is_calculation_mode, false),
        'actual_label', question.actual_label,
        'total_label', question.total_label,
        'is_specific_answer_mode', coalesce(question.is_specific_answer_mode, false),
        'specific_answer_label', question.specific_answer_label
      ) order by question.section_id, question."order", question.id)
      from public.lod_questions question
      join public.lod_sections section on section.id = question.section_id and section.is_active
      where question.is_active
    ), '[]'::jsonb),
    'choices', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', choice.id,
        'question_id', choice.question_id,
        'text', choice.text,
        'points', choice.points,
        'order', choice."order"
      ) order by choice.question_id, choice."order", choice.id)
      from public.lod_choices choice
      join public.lod_questions question on question.id = choice.question_id and question.is_active
      join public.lod_sections section on section.id = question.section_id and section.is_active
      where choice.is_active
    ), '[]'::jsonb),
    'levels', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', config.id,
        'level', config.level,
        'min_score', config.min_score,
        'max_score', config.max_score
      ) order by config.level)
      from public.lod_level_configs config
    ), '[]'::jsonb)
  );
$$;

insert into public.lod_questionnaire_versions (version_number, effective_year, label, config)
select 1, 1900, 'Legacy configuration snapshot', public.build_lod_questionnaire_config()
where not exists (select 1 from public.lod_questionnaire_versions);

update public.lod_assessments assessment
set questionnaire_version_id = (
  select version.id
  from public.lod_questionnaire_versions version
  order by version.version_number asc
  limit 1
)
where assessment.questionnaire_version_id is null;

create or replace function public.get_lod_effective_level(p_assessment public.lod_assessments)
returns integer
language sql
immutable
as $$
  select case
    when coalesce(p_assessment.is_dropped, false) then null
    when p_assessment.manual_level between 1 and 5 then p_assessment.manual_level
    when coalesce(p_assessment.is_complete, false) and p_assessment.computed_level between 1 and 5 then p_assessment.computed_level
    when coalesce(p_assessment.is_carried_over, false) and p_assessment.carried_over_level between 1 and 5 then p_assessment.carried_over_level
    else null
  end;
$$;

-- Backfill only deterministic legacy carry-over rows that have one latest valid earlier source.
with carry_sources as (
  select target.id as target_id, source.id as source_id, source.year as source_year,
         public.get_lod_effective_level(source) as source_level, source.total_score as source_score
  from public.lod_assessments target
  cross join lateral (
    select candidate.*
    from public.lod_assessments candidate
    where candidate.ipo_id = target.ipo_id
      and candidate.year < target.year
      and public.get_lod_effective_level(candidate) is not null
    order by candidate.year desc, candidate.id desc
    limit 1
  ) source
  where target.is_carried_over
    and target.carried_over_from_assessment_id is null
)
update public.lod_assessments target
set carried_over_from_assessment_id = source.source_id,
    carried_over_from_year = source.source_year,
    carried_over_level = source.source_level,
    carried_over_total_score = source.source_score
from carry_sources source
where target.id = source.target_id;

create or replace function public.audit_legacy_lod_carry_over()
returns table (
  assessment_id integer,
  ipo_id integer,
  assessment_year integer,
  has_source boolean,
  source_assessment_id integer,
  source_year integer,
  source_level integer,
  needs_review boolean
)
language sql
stable
as $$
  select assessment.id, assessment.ipo_id, assessment.year,
         assessment.carried_over_from_assessment_id is not null,
         assessment.carried_over_from_assessment_id,
         assessment.carried_over_from_year,
         assessment.carried_over_level,
         assessment.is_carried_over and (
           assessment.carried_over_from_assessment_id is null
           or assessment.carried_over_level is null
         )
  from public.lod_assessments assessment
  where assessment.is_carried_over
  order by assessment.year desc, assessment.ipo_id;
$$;

create or replace function public.resolve_lod_level_from_config(p_score numeric, p_config jsonb)
returns integer
language sql
stable
as $$
  with levels as (
    select (entry->>'level')::integer as level,
           (entry->>'max_score')::numeric as max_score
    from jsonb_array_elements(coalesce(p_config->'levels', '[]'::jsonb)) entry
    where (entry->>'level')::integer between 1 and 5
  )
  select coalesce(
    (select level from levels where p_score <= max_score order by max_score, level limit 1),
    (select level from levels order by max_score desc, level desc limit 1)
  );
$$;

create or replace function public.calculate_lod_assessment(p_assessment_id integer)
returns table (
  total_score numeric,
  computed_level integer,
  is_complete boolean,
  answered_question_count integer,
  required_question_count integer
)
language sql
stable
as $$
  with assessment_config as (
    select version.config
    from public.lod_assessments assessment
    join public.lod_questionnaire_versions version on version.id = assessment.questionnaire_version_id
    where assessment.id = p_assessment_id
  ),
  sections as (
    select (entry->>'id')::integer as id,
           greatest(coalesce((entry->>'weight')::numeric, 0), 0) as weight
    from assessment_config, jsonb_array_elements(coalesce(config->'sections', '[]'::jsonb)) entry
  ),
  questions as (
    select (entry->>'id')::integer as id, (entry->>'section_id')::integer as section_id
    from assessment_config, jsonb_array_elements(coalesce(config->'questions', '[]'::jsonb)) entry
  ),
  choices as (
    select (entry->>'id')::integer as id, (entry->>'question_id')::integer as question_id,
           greatest(coalesce((entry->>'points')::numeric, 0), 0) as points
    from assessment_config, jsonb_array_elements(coalesce(config->'choices', '[]'::jsonb)) entry
  ),
  question_config as (
    select question.id as question_id, question.section_id, max(section.weight) as section_weight,
           max(choice.points) as max_choice_points
    from questions question
    join sections section on section.id = question.section_id
    join choices choice on choice.question_id = question.id
    group by question.id, question.section_id
    having max(choice.points) > 0 and max(section.weight) > 0
  ),
  valid_answers as (
    select config.question_id, config.section_id, choice.points as earned_points
    from question_config config
    join public.lod_answers answer on answer.assessment_id = p_assessment_id and answer.question_id = config.question_id
    join choices choice on choice.id = answer.choice_id and choice.question_id = config.question_id
  ),
  section_rollup as (
    select config.section_id, max(config.section_weight) as section_weight,
           count(config.question_id)::integer as required_questions,
           count(answer.question_id)::integer as answered_questions,
           coalesce(sum(answer.earned_points), 0)::numeric as earned_points,
           coalesce(sum(config.max_choice_points) filter (where answer.question_id is not null), 0)::numeric as possible_points
    from question_config config
    left join valid_answers answer on answer.question_id = config.question_id
    group by config.section_id
  ),
  totals as (
    select coalesce(sum(section_weight), 0)::numeric as configured_weight,
           coalesce(sum(section_weight) filter (where answered_questions > 0), 0)::numeric as answered_section_weight,
           coalesce(sum(case when answered_questions > 0 and possible_points > 0 then (earned_points / possible_points) * section_weight else 0 end), 0)::numeric as earned_weighted_score,
           coalesce(sum(answered_questions), 0)::integer as answered_count,
           coalesce(sum(required_questions), 0)::integer as required_count
    from section_rollup
  ),
  score as (
    select case when configured_weight > 0 and answered_section_weight > 0 then (earned_weighted_score / answered_section_weight) * configured_weight else 0 end::numeric as score_value,
           (required_count > 0 and answered_count = required_count) as complete_value,
           answered_count, required_count
    from totals
  )
  select score_value,
         case when complete_value then public.resolve_lod_level_from_config(score_value, (select config from assessment_config)) else null end,
         complete_value, answered_count, required_count
  from score;
$$;

drop function if exists public.save_lod_assessment(integer, integer, jsonb, integer, text, boolean, boolean, text, bigint, text);

create or replace function public.save_lod_assessment(
  p_ipo_id integer,
  p_year integer,
  p_answers jsonb default '[]'::jsonb,
  p_manual_level integer default null,
  p_manual_override_reason text default null,
  p_is_carried_over boolean default false,
  p_carried_over_from_assessment_id integer default null,
  p_is_dropped boolean default false,
  p_remarks text default null,
  p_assessed_by bigint default null,
  p_assessor_name text default null
)
returns public.lod_assessments
language plpgsql
as $$
declare
  v_assessment public.lod_assessments%rowtype;
  v_existing public.lod_assessments%rowtype;
  v_source public.lod_assessments%rowtype;
  v_version_id bigint;
  v_version_config jsonb;
  v_answer jsonb;
  v_question_id integer;
  v_choice_id integer;
  v_choice_points numeric;
  v_calculation record;
  v_source_level integer;
begin
  if p_year < 1900 or p_year > 2200 then raise exception 'Invalid assessment year.'; end if;
  if p_manual_level is not null and (p_manual_level < 1 or p_manual_level > 5) then raise exception 'Manual level must be between 1 and 5.'; end if;
  if p_manual_level is not null and nullif(trim(p_manual_override_reason), '') is null then raise exception 'A reason is required for a manual level override.'; end if;
  if jsonb_typeof(coalesce(p_answers, '[]'::jsonb)) <> 'array' then raise exception 'LOD answers must be a JSON array.'; end if;

  select * into v_existing from public.lod_assessments where ipo_id = p_ipo_id and year = p_year;
  v_version_id := v_existing.questionnaire_version_id;
  if v_version_id is null then
    select id into v_version_id from public.lod_questionnaire_versions
    where effective_year <= p_year order by effective_year desc, version_number desc limit 1;
  end if;
  if v_version_id is null then raise exception 'No LOD questionnaire version is available for year %.', p_year; end if;
  select config into v_version_config from public.lod_questionnaire_versions where id = v_version_id;

  if coalesce(p_is_carried_over, false) then
    if p_carried_over_from_assessment_id is null then raise exception 'Select a valid earlier assessment to carry over.'; end if;
    select * into v_source from public.lod_assessments where id = p_carried_over_from_assessment_id;
    v_source_level := public.get_lod_effective_level(v_source);
    if not found or v_source.ipo_id <> p_ipo_id or v_source.year >= p_year or v_source_level is null then
      raise exception 'The selected carry-over source is not a valid earlier published assessment.';
    end if;
  else
    v_source_level := null;
  end if;

  insert into public.lod_assessments (
    ipo_id, year, total_score, computed_level, manual_level, manual_override_reason,
    is_carried_over, carried_over_from_assessment_id, carried_over_from_year, carried_over_level,
    carried_over_total_score, questionnaire_version_id, is_dropped, remarks, assessed_by, assessor_name, updated_at
  ) values (
    p_ipo_id, p_year, 0, 0, p_manual_level,
    case when p_manual_level is null then null else trim(p_manual_override_reason) end,
    coalesce(p_is_carried_over, false), case when p_is_carried_over then v_source.id else null end,
    case when p_is_carried_over then v_source.year else null end, case when p_is_carried_over then v_source_level else null end,
    case when p_is_carried_over then v_source.total_score else null end, v_version_id,
    coalesce(p_is_dropped, false), p_remarks, p_assessed_by, p_assessor_name, now()
  )
  on conflict (ipo_id, year) do update set
    manual_level = excluded.manual_level,
    manual_override_reason = excluded.manual_override_reason,
    is_carried_over = excluded.is_carried_over,
    carried_over_from_assessment_id = excluded.carried_over_from_assessment_id,
    carried_over_from_year = excluded.carried_over_from_year,
    carried_over_level = excluded.carried_over_level,
    carried_over_total_score = excluded.carried_over_total_score,
    questionnaire_version_id = coalesce(public.lod_assessments.questionnaire_version_id, excluded.questionnaire_version_id),
    is_dropped = excluded.is_dropped, remarks = excluded.remarks, assessed_by = excluded.assessed_by,
    assessor_name = excluded.assessor_name, updated_at = now()
  returning * into v_assessment;

  delete from public.lod_answers existing
  where existing.assessment_id = v_assessment.id
    and not exists (
      select 1 from jsonb_array_elements(coalesce(p_answers, '[]'::jsonb)) incoming
      where (incoming->>'question_id')::integer = existing.question_id and incoming->>'choice_id' is not null
    );

  for v_answer in select value from jsonb_array_elements(coalesce(p_answers, '[]'::jsonb)) loop
    v_question_id := nullif(v_answer->>'question_id', '')::integer;
    v_choice_id := nullif(v_answer->>'choice_id', '')::integer;
    if v_question_id is null or v_choice_id is null then raise exception 'Every saved LOD answer requires a question and choice.'; end if;
    select greatest(coalesce((choice->>'points')::numeric, 0), 0) into v_choice_points
    from jsonb_array_elements(coalesce(v_version_config->'choices', '[]'::jsonb)) choice
    where (choice->>'id')::integer = v_choice_id and (choice->>'question_id')::integer = v_question_id;
    if not found then raise exception 'Choice % is not valid for question % in this assessment version.', v_choice_id, v_question_id; end if;

    insert into public.lod_answers (assessment_id, question_id, choice_id, points_earned, remarks, actual_value, total_value, specific_answer_value, updated_at)
    values (v_assessment.id, v_question_id, v_choice_id, v_choice_points, nullif(v_answer->>'remarks', ''),
      nullif(v_answer->>'actual_value', '')::numeric, nullif(v_answer->>'total_value', '')::numeric,
      nullif(v_answer->>'specific_answer_value', ''), now())
    on conflict (assessment_id, question_id) do update set
      choice_id = excluded.choice_id, points_earned = excluded.points_earned, remarks = excluded.remarks,
      actual_value = excluded.actual_value, total_value = excluded.total_value,
      specific_answer_value = excluded.specific_answer_value, updated_at = now();
  end loop;

  select * into v_calculation from public.calculate_lod_assessment(v_assessment.id);
  update public.lod_assessments set total_score = v_calculation.total_score,
    computed_level = coalesce(v_calculation.computed_level, 0), is_complete = v_calculation.is_complete,
    answered_question_count = v_calculation.answered_question_count,
    required_question_count = v_calculation.required_question_count, updated_at = now()
  where id = v_assessment.id returning * into v_assessment;
  return v_assessment;
end;
$$;

create or replace function public.bulk_save_lod_admin_states(
  p_rows jsonb,
  p_assessed_by bigint default null,
  p_assessor_name text default null
)
returns setof public.lod_assessments
language plpgsql
as $$
declare
  row_data jsonb;
  row_ipo_id integer;
  row_year integer;
  row_manual integer;
  row_reason text;
  row_dropped boolean;
  version_id bigint;
begin
  if jsonb_typeof(coalesce(p_rows, '[]'::jsonb)) <> 'array' then raise exception 'Import rows must be a JSON array.'; end if;
  if exists (
    select 1 from jsonb_array_elements(p_rows) row_item
    group by (row_item->>'ipo_id')::integer, (row_item->>'year')::integer having count(*) > 1
  ) then raise exception 'The import contains duplicate IPO/year rows.'; end if;

  for row_data in select value from jsonb_array_elements(p_rows) loop
    row_ipo_id := nullif(row_data->>'ipo_id', '')::integer;
    row_year := nullif(row_data->>'year', '')::integer;
    row_manual := nullif(row_data->>'manual_level', '')::integer;
    row_reason := nullif(trim(row_data->>'manual_override_reason'), '');
    row_dropped := coalesce((row_data->>'is_dropped')::boolean, false);
    if row_ipo_id is null or not exists (select 1 from public.ipos where id = row_ipo_id) then raise exception 'Invalid IPO id in import.'; end if;
    if row_year is null or row_year < 1900 or row_year > 2200 then raise exception 'Invalid assessment year in import.'; end if;
    if row_manual is not null and (row_manual < 1 or row_manual > 5 or row_reason is null) then raise exception 'Every manual level requires a valid level and reason.'; end if;
  end loop;

  for row_data in select value from jsonb_array_elements(p_rows) loop
    row_ipo_id := (row_data->>'ipo_id')::integer;
    row_year := (row_data->>'year')::integer;
    row_manual := nullif(row_data->>'manual_level', '')::integer;
    row_reason := nullif(trim(row_data->>'manual_override_reason'), '');
    row_dropped := coalesce((row_data->>'is_dropped')::boolean, false);
    select id into version_id from public.lod_questionnaire_versions where effective_year <= row_year order by effective_year desc, version_number desc limit 1;
    insert into public.lod_assessments (
      ipo_id, year, total_score, computed_level, manual_level, manual_override_reason,
      questionnaire_version_id, is_dropped, is_complete, answered_question_count,
      required_question_count, assessed_by, assessor_name, updated_at
    )
    values (
      row_ipo_id, row_year, 0, 0, row_manual, row_reason, version_id, row_dropped,
      false, 0, 0, p_assessed_by, p_assessor_name, now()
    )
    on conflict (ipo_id, year) do update set manual_level = excluded.manual_level,
      manual_override_reason = excluded.manual_override_reason, is_dropped = excluded.is_dropped,
      assessed_by = excluded.assessed_by, assessor_name = excluded.assessor_name, updated_at = now();
  end loop;

  return query
  select assessment.* from public.lod_assessments assessment
  join jsonb_array_elements(p_rows) row_item
    on assessment.ipo_id = (row_item->>'ipo_id')::integer and assessment.year = (row_item->>'year')::integer;
end;
$$;

create or replace function public.save_lod_questionnaire_configuration(
  p_sections jsonb,
  p_questions jsonb,
  p_choices jsonb,
  p_levels jsonb,
  p_effective_year integer,
  p_created_by bigint default null,
  p_created_by_name text default null
)
returns public.lod_questionnaire_versions
language plpgsql
as $$
declare
  section_data jsonb;
  question_data jsonb;
  choice_data jsonb;
  level_data jsonb;
  client_id integer;
  parent_client_id integer;
  persisted_id integer;
  parent_persisted_id integer;
  section_map jsonb := '{}'::jsonb;
  question_map jsonb := '{}'::jsonb;
  next_version integer;
  saved_version public.lod_questionnaire_versions%rowtype;
begin
  if p_effective_year < 1900 or p_effective_year > 2200 then
    raise exception 'Invalid questionnaire effective year.';
  end if;
  if jsonb_typeof(coalesce(p_sections, '[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_questions, '[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_choices, '[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_levels, '[]'::jsonb)) <> 'array' then
    raise exception 'LOD configuration payloads must be JSON arrays.';
  end if;
  if jsonb_array_length(coalesce(p_sections, '[]'::jsonb)) = 0 then
    raise exception 'At least one active LOD section is required.';
  end if;
  if jsonb_array_length(coalesce(p_levels, '[]'::jsonb)) <> 5 then
    raise exception 'LOD level configuration must contain Levels 1 through 5.';
  end if;
  if exists (
    select 1 from (
      select entry->>'id' as id
      from jsonb_array_elements(p_sections) entry
      group by entry->>'id' having count(*) > 1
    ) duplicate_section
  ) or exists (
    select 1 from (
      select entry->>'id' as id
      from jsonb_array_elements(p_questions) entry
      group by entry->>'id' having count(*) > 1
    ) duplicate_question
  ) or exists (
    select 1 from (
      select entry->>'id' as id
      from jsonb_array_elements(p_choices) entry
      group by entry->>'id' having count(*) > 1
    ) duplicate_choice
  ) then
    raise exception 'LOD configuration contains duplicate section, question, or choice identifiers.';
  end if;
  if (
    select count(distinct (entry->>'level')::integer)
    from jsonb_array_elements(p_levels) entry
    where (entry->>'level')::integer between 1 and 5
  ) <> 5 then
    raise exception 'LOD level configuration must contain each level from 1 through 5 exactly once.';
  end if;
  if exists (
    with ranges as (
      select (entry->>'level')::integer as level,
             (entry->>'min_score')::numeric as min_score,
             (entry->>'max_score')::numeric as max_score
      from jsonb_array_elements(p_levels) entry
    ), ordered as (
      select ranges.*, lag(max_score) over (order by level) as previous_max
      from ranges
    )
    select 1 from ordered
    where min_score > max_score
       or (previous_max is not null and (min_score <> previous_max or max_score <= previous_max))
  ) then
    raise exception 'LOD level ranges must be ascending and contiguous.';
  end if;

  update public.lod_choices set is_active = false where is_active;
  update public.lod_questions set is_active = false where is_active;
  update public.lod_sections set is_active = false where is_active;

  for section_data in select value from jsonb_array_elements(coalesce(p_sections, '[]'::jsonb)) loop
    client_id := nullif(section_data->>'id', '')::integer;
    if client_id is null or nullif(trim(section_data->>'title'), '') is null then
      raise exception 'Every LOD section requires an id and title.';
    end if;
    if client_id > 0 then
      update public.lod_sections
      set title = trim(section_data->>'title'), code = nullif(trim(section_data->>'code'), ''),
          "order" = coalesce((section_data->>'order')::integer, 0),
          weight = greatest(coalesce((section_data->>'weight')::numeric, 0), 0), is_active = true
      where id = client_id returning id into persisted_id;
      if not found then raise exception 'LOD section % no longer exists.', client_id; end if;
    else
      insert into public.lod_sections (title, code, "order", weight, is_active)
      values (trim(section_data->>'title'), nullif(trim(section_data->>'code'), ''),
              coalesce((section_data->>'order')::integer, 0),
              greatest(coalesce((section_data->>'weight')::numeric, 0), 0), true)
      returning id into persisted_id;
    end if;
    section_map := jsonb_set(section_map, array[client_id::text], to_jsonb(persisted_id), true);
  end loop;

  for question_data in select value from jsonb_array_elements(coalesce(p_questions, '[]'::jsonb)) loop
    client_id := nullif(question_data->>'id', '')::integer;
    parent_client_id := nullif(question_data->>'section_id', '')::integer;
    parent_persisted_id := nullif(section_map->>parent_client_id::text, '')::integer;
    if client_id is null or parent_persisted_id is null or nullif(trim(question_data->>'text'), '') is null then
      raise exception 'Every LOD question requires an id, active section, and question text.';
    end if;
    if client_id > 0 then
      update public.lod_questions
      set section_id = parent_persisted_id, text = trim(question_data->>'text'),
          code = nullif(trim(question_data->>'code'), ''), description = nullif(question_data->>'description', ''),
          weight = greatest(coalesce((question_data->>'weight')::numeric, 0), 0),
          "order" = coalesce((question_data->>'order')::integer, 0),
          is_calculation_mode = coalesce((question_data->>'is_calculation_mode')::boolean, false),
          actual_label = nullif(question_data->>'actual_label', ''), total_label = nullif(question_data->>'total_label', ''),
          is_specific_answer_mode = coalesce((question_data->>'is_specific_answer_mode')::boolean, false),
          specific_answer_label = nullif(question_data->>'specific_answer_label', ''), is_active = true
      where id = client_id returning id into persisted_id;
      if not found then raise exception 'LOD question % no longer exists.', client_id; end if;
    else
      insert into public.lod_questions (
        section_id, text, code, description, weight, "order", is_calculation_mode,
        actual_label, total_label, is_specific_answer_mode, specific_answer_label, is_active
      ) values (
        parent_persisted_id, trim(question_data->>'text'), nullif(trim(question_data->>'code'), ''),
        nullif(question_data->>'description', ''), greatest(coalesce((question_data->>'weight')::numeric, 0), 0),
        coalesce((question_data->>'order')::integer, 0), coalesce((question_data->>'is_calculation_mode')::boolean, false),
        nullif(question_data->>'actual_label', ''), nullif(question_data->>'total_label', ''),
        coalesce((question_data->>'is_specific_answer_mode')::boolean, false),
        nullif(question_data->>'specific_answer_label', ''), true
      ) returning id into persisted_id;
    end if;
    question_map := jsonb_set(question_map, array[client_id::text], to_jsonb(persisted_id), true);
  end loop;

  for choice_data in select value from jsonb_array_elements(coalesce(p_choices, '[]'::jsonb)) loop
    client_id := nullif(choice_data->>'id', '')::integer;
    parent_client_id := nullif(choice_data->>'question_id', '')::integer;
    parent_persisted_id := nullif(question_map->>parent_client_id::text, '')::integer;
    if client_id is null or parent_persisted_id is null or nullif(trim(choice_data->>'text'), '') is null then
      raise exception 'Every LOD choice requires an id, active question, and answer text.';
    end if;
    if client_id > 0 then
      update public.lod_choices
      set question_id = parent_persisted_id, text = trim(choice_data->>'text'),
          points = greatest(coalesce((choice_data->>'points')::numeric, 0), 0),
          "order" = coalesce((choice_data->>'order')::integer, 0), is_active = true
      where id = client_id returning id into persisted_id;
      if not found then raise exception 'LOD choice % no longer exists.', client_id; end if;
    else
      insert into public.lod_choices (question_id, text, points, "order", is_active)
      values (parent_persisted_id, trim(choice_data->>'text'),
              greatest(coalesce((choice_data->>'points')::numeric, 0), 0),
              coalesce((choice_data->>'order')::integer, 0), true)
      returning id into persisted_id;
    end if;
  end loop;

  if coalesce((select sum(weight) from public.lod_sections where is_active), 0) <= 0 then
    raise exception 'Active LOD sections must have a positive total weight.';
  end if;
  if exists (
    select 1
    from public.lod_questions question
    where question.is_active
      and not exists (
        select 1 from public.lod_choices choice
        where choice.question_id = question.id
          and choice.is_active
          and choice.points > 0
      )
  ) then
    raise exception 'Every active LOD question requires at least one active choice with positive points.';
  end if;

  for level_data in select value from jsonb_array_elements(coalesce(p_levels, '[]'::jsonb)) loop
    if (level_data->>'level')::integer not between 1 and 5
       or (level_data->>'min_score')::numeric > (level_data->>'max_score')::numeric then
      raise exception 'Invalid LOD level range.';
    end if;
    update public.lod_level_configs
    set min_score = (level_data->>'min_score')::numeric,
        max_score = (level_data->>'max_score')::numeric,
        updated_at = now()
    where level = (level_data->>'level')::integer;
    if not found then raise exception 'LOD level % is missing.', level_data->>'level'; end if;
  end loop;

  select coalesce(max(version_number), 0) + 1 into next_version
  from public.lod_questionnaire_versions;
  insert into public.lod_questionnaire_versions (
    version_number, effective_year, label, config, created_by, created_by_name
  ) values (
    next_version, p_effective_year, format('LOD questionnaire v%s', next_version),
    public.build_lod_questionnaire_config(), p_created_by, p_created_by_name
  ) returning * into saved_version;

  return saved_version;
end;
$$;

grant select on public.lod_questionnaire_versions to anon, authenticated;
grant execute on function public.build_lod_questionnaire_config() to authenticated;
grant execute on function public.audit_legacy_lod_carry_over() to authenticated;
grant execute on function public.save_lod_assessment(integer, integer, jsonb, integer, text, boolean, integer, boolean, text, bigint, text) to anon, authenticated;
grant execute on function public.bulk_save_lod_admin_states(jsonb, bigint, text) to authenticated;
grant execute on function public.save_lod_questionnaire_configuration(jsonb, jsonb, jsonb, jsonb, integer, bigint, text) to authenticated;
